# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sentiment_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sentiment_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data